[env:m5stick-c]
platform = espressif32
board = m5stick-c
framework = arduino
monitor_speed = 115200
; upload_port = /dev/cu.usbserial-XXXX   ; uncomment/set if auto-detect fails
lib_deps = m5stack/M5Unified
